# Docker Compose for backend services only (recommended for Electron development)

services:
  # Backend Only - CORE FastAPI Application
  core-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: core-backend
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
      - CORE_ENV=development
      - DATABASE_URL=postgresql://core_user:core_password@postgres:5432/core_db
      - REDIS_URL=redis://redis:6379
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./backend:/app
      - backend-data:/app/data
    networks:
      - core-network
    depends_on:
      - postgres
      - redis
      - ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database - PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: core-postgres
    environment:
      - POSTGRES_DB=core_db
      - POSTGRES_USER=core_user
      - POSTGRES_PASSWORD=core_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - core-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U core_user -d core_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis - For caching and session management
  redis:
    image: redis:7-alpine
    container_name: core-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - core-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Local LLM Inference - Ollama (for local models)
  ollama:
    image: ollama/ollama:latest
    container_name: core-ollama
    ports:
      - "11434:11434"
    volumes:
      # - ollama-data:/root/.ollama
      # To reuse host-installed models, replace the line above with a bind mount to your host models directory.
      - C:/Users/Owner/.ollama:/root/.ollama
      # On Windows (adjust user name if needed):
      # - C:/Users/Owner/.ollama:/root/.ollama
      # On macOS/Linux:
      # - ~/.ollama:/root/.ollama
    networks:
      - core-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  backend-data:
  postgres-data:
  redis-data:
  ollama-data:

networks:
  core-network:
    driver: bridge